image:
  name: vault
  # Leaving tag empty will use the Chart.appVersion
  tag: "latest"
  pullPolicy: IfNotPresent

mongo:
  uri: "mongodb://$USERNAME:$PASSWORD@mongodb.default.svc.cluster.local:27017"

kafka:
  servers: "kafka.default.svc.cluster.local:9092"

service:
  port: 50011

resources:
  limits:
    cpu: 4000m
  requests:
    cpu: 2000m

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  averageUtilization: 30

nodeSelector: {}

tolerations: []

affinity: {}
