image:
  name: vault
  # Leaving tag empty will use the Chart.appVersion
  tag: "latest"
  pullPolicy: IfNotPresent

mongo:
  uri: "mongodb://$USERNAME:$PASSWORD@mongodb.default.svc.cluster.local:27017"

kafka:
  servers: "kafka.default.svc.cluster.local:9092"

service:
  port: 50011

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
