image:
  name: vault
  # Leaving tag empty will use the Chart.appVersion
  tag: "latest"
  pullPolicy: IfNotPresent

mongo:
  uri: "mongodb://$USERNAME:$PASSWORD@mongodb.default.svc.cluster.local:27017"

kafka:
  servers: "kafka.default.svc.cluster.local:9092"

service:
  port: 50011

# Do NOT enable this in production - vault is not designed as an edge service.
# The ingress is here for local testing only.
ingress:
  enabled: false

resources:
  limits:
    cpu: 4000m
    memory: 150Mi
  requests:
    cpu: 200m
    memory: 50Mi

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  averageUtilization: 30

nodeSelector: {}

tolerations: []

affinity: {}
