# Leaving tag empty will use the Chart.appVersion
image:
  name: vault
  tag: "latest"
  pullPolicy: IfNotPresent

mongo:
  uri: "mongodb://$USERNAME:$PASSWORD@mongodb.default.svc.cluster.local:27017"

kafka:
  servers: "kafka.default.svc.cluster.local:9092"

service:
  port: 50011

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
